# This is a basic workflow to help you get started with Actions
name: re
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
#  push:
#    branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]
  schedule:
    # UTC (国内 UTC+8)
    - cron: '* * * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    curl -s https://ygtro.ygabc.repl.co
